version: '3.8'

services:

  db:
    image: postgres:15.1
    ports:
      - "7788:5432"
    env_file: app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.4
    container_name: red_cas
    env_file: app/.env
    ports:
      - "2279:6379"
    volumes:
      - redis_data:/var/lib/redis/data/

  backend:
    build: app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/webtron
    command: sh -c " alembic upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 "
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  redis_data:
